version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  php:
    build:
      context: ./dockerfiles/php
      dockerfile: Dockerfile
    image: php
    container_name: my-php-container
    working_dir: /var/www/html
    entrypoint: ["sh", "-c", "composer install && exec apache2-foreground"]
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: 'no'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  src:
  postgres_data: